#!/bin/sh

MODULE="/oem/usr/ko/esp32_spi.ko"
MODULE_NAME="esp32_spi"
RESET_PIN=54

WLAN=wlan0

WPA_CONF="/etc/wpa_supplicant.conf"

# WiFi configuration
WIFI_SSID="FRITZ!Box 7530 YZ"
WIFI_PSK="22847804674596686441"

generate_wpa_config()
{
    echo "Generating $WPA_CONF"

    cat > "$WPA_CONF" <<EOF
ctrl_interface=/var/run/wpa_supplicant
ap_scan=1
update_config=1

network={
    ssid="$WIFI_SSID"
    psk="$WIFI_PSK"
    key_mgmt=WPA-PSK
}
EOF

    chmod 600 "$WPA_CONF"
}


start()
{
    echo "Loading ESP-Hosted"

    if ! lsmod | grep -q "^${MODULE_NAME}\b"; then
        insmod "$MODULE" resetpin=$RESET_PIN || return 1
    fi

    echo "Waiting for wlan0..."

    for i in $(seq 1 20)
    do
        ip link show "$WLAN" >/dev/null 2>&1 && break
        sleep 1
    done

    if ! ip link show "$WLAN" >/dev/null 2>&1
    then
        echo "ERROR: wlan0 not found"
        return 1
    fi


    generate_wpa_config


    killall wpa_supplicant 2>/dev/null
    killall wpa_cli 2>/dev/null

    echo "Starting wpa_supplicant"

    wpa_supplicant \
        -B \
        -i "$WLAN" \
        -c "$WPA_CONF"


    echo "Starting event handler"

    wpa_cli \
        -B \
        -i "$WLAN" \
        -a /usr/bin/wifi-action.sh
}


stop()
{
    killall wpa_cli 2>/dev/null
    killall wpa_supplicant 2>/dev/null

    rmmod "$MODULE_NAME"
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 2
        start
        ;;
esac

exit 0
