#!/bin/sh

MODULE="/root/esp32_spi.ko"
MODULE_NAME="esp32_spi"
RESET_PIN=54

WLAN=wlan0

start()
{
    echo "Loading ESP-Hosted"

    if ! lsmod | grep -q "^${MODULE_NAME}\b"; then
        insmod "$MODULE" resetpin=$RESET_PIN || return 1
    fi

    echo "Waiting for wlan0..."

    for i in $(seq 1 20)
    do
        ip link show "$WLAN" >/dev/null 2>&1 && break
        sleep 1
    done

    if ! ip link show "$WLAN" >/dev/null 2>&1
    then
        echo "ERROR: wlan0 not found"
        return 1
    fi

    killall wpa_supplicant 2>/dev/null
    killall wpa_cli 2>/dev/null

    echo "Starting wpa_supplicant"

    wpa_supplicant \
        -B \
        -i "$WLAN" \
        -c /etc/wpa_supplicant.conf

    echo "Starting event handler"

    wpa_cli \
        -B \
        -i "$WLAN" \
        -a /usr/bin/wifi-action.sh
}

stop()
{
    killall wpa_cli 2>/dev/null
    killall wpa_supplicant 2>/dev/null

    rmmod "$MODULE_NAME"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 2
        start
        ;;
esac

exit 0
